<?php
require_once __DIR__ . '/rector_common.php';

$pdo->exec("CREATE TABLE IF NOT EXISTS asistencia (id_asistencia INT NOT NULL AUTO_INCREMENT PRIMARY KEY, id_matricula INT NOT NULL, fecha DATE NOT NULL, estado ENUM('presente','ausente') NOT NULL, UNIQUE KEY asistencia_dia (id_matricula, fecha)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$stats = rector_stats($pdo);
$resumen = $pdo->query("SELECT u.nombre AS estudiante, c.nombre AS curso, COUNT(DISTINCT CASE WHEN a.estado = 'presente' THEN a.id_asistencia END) AS asistencias, COUNT(DISTINCT CASE WHEN a.estado = 'ausente' THEN a.id_asistencia END) AS faltas, COUNT(DISTINCT o.id_observacion) AS observaciones FROM matricula mat JOIN usuario u ON mat.id_estudiante = u.id_usuario JOIN asignacion_academica aa ON mat.id_asignacion = aa.id_asignacion JOIN curso c ON aa.id_curso = c.id_curso LEFT JOIN asistencia a ON a.id_matricula = mat.id_matricula LEFT JOIN observador o ON o.id_estudiante = mat.id_estudiante AND o.id_asignacion = mat.id_asignacion GROUP BY mat.id_matricula, u.id_usuario, c.id_curso ORDER BY u.nombre, c.nombre")->fetchAll();
$observaciones = $pdo->query("SELECT o.descripcion, o.fecha, u.nombre AS estudiante, d.nombre AS docente, m.nombre AS materia, c.nombre AS curso FROM observador o JOIN usuario u ON o.id_estudiante = u.id_usuario JOIN asignacion_academica aa ON o.id_asignacion = aa.id_asignacion JOIN usuario d ON aa.id_docente = d.id_usuario JOIN materia m ON aa.id_materia = m.id_materia JOIN curso c ON aa.id_curso = c.id_curso ORDER BY o.fecha DESC LIMIT 30")->fetchAll();

rector_layout_start('Reportes Generales', 'reportes');
?>
<div class="section-title"><i class="fa-solid fa-chart-bar"></i> Reportes Académicos</div>
<div class="stats-grid"><?php foreach ([['blue','fa-users',$stats['usuarios'],'Usuarios totales'],['green','fa-user-graduate',$stats['estudiantes'],'Estudiantes'],['orange','fa-chalkboard-user',$stats['docentes'],'Docentes'],['purple','fa-door-open',$stats['cursos'],'Cursos activos']] as [$clase,$icono,$valor,$etiqueta]): ?><div class="stat-card"><div class="stat-icon <?= $clase ?>"><i class="fa-solid <?= $icono ?>"></i></div><div class="stat-body"><div class="stat-value"><?= $valor ?></div><div class="stat-label"><?= $etiqueta ?></div></div></div><?php endforeach; ?></div>
<div class="card"><div class="card-title"><i class="fa-solid fa-user-check"></i> Asistencia por estudiante</div><?php if (!$resumen): ?><div class="empty-state"><i class="fa-solid fa-chart-simple"></i><p>Aún no hay estudiantes matriculados.</p></div><?php else: ?><div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>Curso</th><th>Asistió</th><th>Faltó</th><th>Observaciones</th></tr></thead><tbody><?php foreach ($resumen as $fila): ?><tr><td><?= htmlspecialchars($fila['estudiante']) ?></td><td><span class="badge blue"><?= htmlspecialchars($fila['curso']) ?></span></td><td><span class="badge green"><?= (int)$fila['asistencias'] ?></span></td><td><span class="badge red"><?= (int)$fila['faltas'] ?></span></td><td><?= (int)$fila['observaciones'] ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div class="card" style="margin-top:1.25rem"><div class="card-title"><i class="fa-solid fa-triangle-exclamation"></i> Observaciones registradas por docentes</div><?php if (!$observaciones): ?><div class="empty-state"><i class="fa-solid fa-clipboard-check"></i><p>No hay observaciones registradas.</p></div><?php else: ?><div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>Curso</th><th>Materia</th><th>Docente</th><th>Observación</th><th>Fecha</th></tr></thead><tbody><?php foreach ($observaciones as $observacion): ?><tr><td><?= htmlspecialchars($observacion['estudiante']) ?></td><td><?= htmlspecialchars($observacion['curso']) ?></td><td><?= htmlspecialchars($observacion['materia']) ?></td><td><?= htmlspecialchars($observacion['docente']) ?></td><td><?= htmlspecialchars($observacion['descripcion']) ?></td><td><?= date('d/m/Y', strtotime($observacion['fecha'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<?php rector_layout_end(); ?>